#!/usr/bin/env zsh

#
# template of concrete functions
# UPDATE code appropriately for your do method
#

dir_name=$( cd $( dirname $0 ); pwd | sed 's/^.*\///' )
do_name=$( basename $0 )
work_name=${dir_name:3}
env_path=${ZSH_COMPLETION_KIT_BASE_DIR}/etc/${work_name}.env
[[ -f $env_path ]] && . $env_path

repo_name_candidate=$1

# output usage information for direct execution
#
function printUsage() {
	echo "Usage: $do_name [args]"
	func_sub_do_help
}

# concrete function to execute something for your do method
# ACTION: Update code
#
function func_sub_do() {
	# here code to be done in this do method
	repo_name=$1
	branch_name=$2
	repo_dir=$( cat $GIT_REPO_LIST | grep "^${repo_name}\t${branch_name}\t" | cut -f3 )
	
	# number of repository record
	l=$( cat $GIT_REPO_LIST | grep "^${repo_name}\t${branch_name}\t" | wc -l )
	
	# check list
	if [[ $l -ne 1 ]]; then
		echo "ERROR: record invalud"
		exit 255
	fi
	
	# check parameters
	if [[ $branch_name = "" ]]; then
		echo "ERROR: branch name not found"
		exit 255
	fi
	if [[ ! -d $repo_dir ]]; then
		echo "ERROR: invalid repo dir $repo_dir"
		exit 255
	fi
	
	( cd $repo_dir ; git push origin ${branch_name} )
	rc=$?
	
	exit $rc
}

# template concrete function to return completion information(key and values) of argument
# ACTION: Duplicate below several times of arguments, Revise function name of argX and Update code
#
function func_sub_return_completion_do_arg1() {
	# here return key/values for completion in this do method
	[[ $1 = "key" ]] && echo "repo name"
	sz_repo_names=( $( cat $GIT_REPO_LIST | grep -v '^#' | grep -v '^$' | cut -f1 ) )
	repo_names="$( IFS=' '; echo "${sz_repo_names[*]}" )"
	[[ $1 = "values" ]] && echo $repo_names
}
function func_sub_return_completion_do_arg2() {
	# here return key/values for completion in this do method
	[[ $1 = "key" ]] && echo "branch name"
	sz_branch_names=( $( cat $GIT_REPO_LIST | grep "^${repo_name_candidate}\t" | cut -f2 ) )
	branch_names="$( IFS=' '; echo "${sz_branch_names[*]}" )"
	[[ $1 = "values" ]] && echo $branch_names
}

# concrete function to output this method description for indirect execution(called from completion _XXX_do script/function)
# ACTION: Update code
#
function func_sub_do_desc() {
	# here output description for this do method
	echo "upload(push) from local repo to remote repo with commit"
}

# concrete function to output arguments usage for indirect execution(called from parent XXX_do script/function)
# ACTION: Update code
#
function func_sub_do_help() {
	# here output arguments usage in this do method
	echo "    arg[1]: repo name"
	echo "    arg[1]: branch name"
}


# example export functions list. all function included.
# ACTION: Uncomment and Delete undefined function appropriate in this do method
#
#export_functions='func_sub_do func_sub_do_desc func_sub_do_help func_sub_return_completion_do_arg1 func_sub_return_completion_do_arg2 func_sub_return_completion_do_arg3 func_sub_return_completion_do_arg4 func_sub_return_completion_do_arg5 func_sub_return_completion_do_arg6 func_sub_return_completion_do_arg7 func_sub_return_completion_do_arg8 func_sub_return_completion_do_arg9'

export_functions='func_sub_do func_sub_do_desc func_sub_do_help func_sub_return_completion_do_arg1 func_sub_return_completion_do_arg2'


# export functions listed in above export_functions variable
export -f $export_functions

# call super shellscript/function like inherited method of super class. And callback the function exported to do concrete action
. $( dirname $0 )/../.do/do.super $1 $2 $3 $4 $5 $6 $7 $8 $9

# unexport functions
unset $export_functions


